/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/router/src/router_module';
import * as import8 from '@angular/common/src/localization';
import * as import9 from '@angular/core/src/application_init';
import * as import10 from '@angular/core/src/testability/testability';
import * as import11 from '@angular/core/src/application_ref';
import * as import12 from '@angular/core/src/linker/compiler';
import * as import13 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import14 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import15 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import16 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import17 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import18 from '@angular/core/src/linker/view_utils';
import * as import19 from '@angular/platform-browser/src/browser/title';
import * as import20 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import21 from '@angular/forms/src/form_builder';
import * as import22 from '@angular/common/src/location/location';
import * as import23 from '@angular/router/src/url_tree';
import * as import24 from '@angular/router/src/router_outlet_map';
import * as import25 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import26 from '@angular/router/src/router_preloader';
import * as import27 from '@angular/core/src/di/injector';
import * as import28 from './messages/messages.component.ngfactory';
import * as import29 from './auth/authentication.component.ngfactory';
import * as import30 from './auth/signup.component.ngfactory';
import * as import31 from './auth/signin.component.ngfactory';
import * as import32 from './auth/logout.component.ngfactory';
import * as import33 from './app.component.ngfactory';
import * as import34 from '@angular/core/src/application_tokens';
import * as import35 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import36 from '@angular/platform-browser/src/dom/events/key_events';
import * as import37 from '@angular/core/src/zone/ng_zone';
import * as import38 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import39 from '@angular/common/src/location/platform_location';
import * as import40 from '@angular/common/src/location/location_strategy';
import * as import41 from './messages/messages.component';
import * as import42 from './auth/authentication.component';
import * as import43 from './auth/signup.component';
import * as import44 from './auth/signin.component';
import * as import45 from './auth/logout.component';
import * as import46 from '@angular/router/src/url_handling_strategy';
import * as import47 from '@angular/router/src/router';
import * as import48 from '@angular/core/src/console';
import * as import49 from '@angular/core/src/i18n/tokens';
import * as import50 from '@angular/core/src/error_handler';
import * as import51 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import52 from '@angular/platform-browser/src/dom/animation_driver';
import * as import53 from '@angular/core/src/render/api';
import * as import54 from '@angular/core/src/security';
import * as import55 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import56 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import57 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import58 from '@angular/router/src/router_config_loader';
import * as import59 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _ROUTER_FORROOT_GUARD_5:any;
  _RouterModule_6:import7.RouterModule;
  _ReactiveFormsModule_7:import6.ReactiveFormsModule;
  _AppModule_8:import1.AppModule;
  __LOCALE_ID_9:any;
  __NgLocalization_10:import8.NgLocaleLocalization;
  _ErrorHandler_11:any;
  _ApplicationInitStatus_12:import9.ApplicationInitStatus;
  _Testability_13:import10.Testability;
  _ApplicationRef__14:import11.ApplicationRef_;
  __ApplicationRef_15:any;
  __Compiler_16:import12.Compiler;
  __APP_ID_17:any;
  __DOCUMENT_18:any;
  __HAMMER_GESTURE_CONFIG_19:import13.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_20:any[];
  __EventManager_21:import14.EventManager;
  __DomSharedStylesHost_22:import15.DomSharedStylesHost;
  __AnimationDriver_23:any;
  __DomRootRenderer_24:import16.DomRootRenderer_;
  __RootRenderer_25:any;
  __DomSanitizer_26:import17.DomSanitizerImpl;
  __Sanitizer_27:any;
  __ViewUtils_28:import18.ViewUtils;
  __IterableDiffers_29:any;
  __KeyValueDiffers_30:any;
  __SharedStylesHost_31:any;
  __Title_32:import19.Title;
  __RadioControlRegistry_33:import20.RadioControlRegistry;
  __FormBuilder_34:import21.FormBuilder;
  __ROUTER_CONFIGURATION_35:any;
  __LocationStrategy_36:any;
  __Location_37:import22.Location;
  __UrlSerializer_38:import23.DefaultUrlSerializer;
  __RouterOutletMap_39:import24.RouterOutletMap;
  __NgModuleFactoryLoader_40:import25.SystemJsNgModuleLoader;
  __ROUTES_41:any[];
  __Router_42:any;
  __ActivatedRoute_43:any;
  _NoPreloading_44:import26.NoPreloading;
  _PreloadingStrategy_45:any;
  _RouterPreloader_46:import26.RouterPreloader;
  __PreloadAllModules_47:import26.PreloadAllModules;
  __ROUTER_INITIALIZER_48:any;
  __APP_BOOTSTRAP_LISTENER_49:any[];
  constructor(parent:import27.Injector) {
    super(parent,[
      import28.MessagesComponentNgFactory,
      import29.AuthenticationComponentNgFactory,
      import30.SignupComponentNgFactory,
      import31.SigninComponentNgFactory,
      import32.LogoutComponentNgFactory,
      import33.AppComponentNgFactory
    ]
    ,[import33.AppComponentNgFactory]);
  }
  get _LOCALE_ID_9():any {
    if ((this.__LOCALE_ID_9 == null)) { (this.__LOCALE_ID_9 = 'en-US'); }
    return this.__LOCALE_ID_9;
  }
  get _NgLocalization_10():import8.NgLocaleLocalization {
    if ((this.__NgLocalization_10 == null)) { (this.__NgLocalization_10 = new import8.NgLocaleLocalization(this._LOCALE_ID_9)); }
    return this.__NgLocalization_10;
  }
  get _ApplicationRef_15():any {
    if ((this.__ApplicationRef_15 == null)) { (this.__ApplicationRef_15 = this._ApplicationRef__14); }
    return this.__ApplicationRef_15;
  }
  get _Compiler_16():import12.Compiler {
    if ((this.__Compiler_16 == null)) { (this.__Compiler_16 = new import12.Compiler()); }
    return this.__Compiler_16;
  }
  get _APP_ID_17():any {
    if ((this.__APP_ID_17 == null)) { (this.__APP_ID_17 = import34._appIdRandomProviderFactory()); }
    return this.__APP_ID_17;
  }
  get _DOCUMENT_18():any {
    if ((this.__DOCUMENT_18 == null)) { (this.__DOCUMENT_18 = import4._document()); }
    return this.__DOCUMENT_18;
  }
  get _HAMMER_GESTURE_CONFIG_19():import13.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_19 == null)) { (this.__HAMMER_GESTURE_CONFIG_19 = new import13.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_19;
  }
  get _EVENT_MANAGER_PLUGINS_20():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_20 == null)) { (this.__EVENT_MANAGER_PLUGINS_20 = [
      new import35.DomEventsPlugin(),
      new import36.KeyEventsPlugin(),
      new import13.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_19)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_20;
  }
  get _EventManager_21():import14.EventManager {
    if ((this.__EventManager_21 == null)) { (this.__EventManager_21 = new import14.EventManager(this._EVENT_MANAGER_PLUGINS_20,this.parent.get(import37.NgZone))); }
    return this.__EventManager_21;
  }
  get _DomSharedStylesHost_22():import15.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_22 == null)) { (this.__DomSharedStylesHost_22 = new import15.DomSharedStylesHost(this._DOCUMENT_18)); }
    return this.__DomSharedStylesHost_22;
  }
  get _AnimationDriver_23():any {
    if ((this.__AnimationDriver_23 == null)) { (this.__AnimationDriver_23 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_23;
  }
  get _DomRootRenderer_24():import16.DomRootRenderer_ {
    if ((this.__DomRootRenderer_24 == null)) { (this.__DomRootRenderer_24 = new import16.DomRootRenderer_(this._DOCUMENT_18,this._EventManager_21,this._DomSharedStylesHost_22,this._AnimationDriver_23,this._APP_ID_17)); }
    return this.__DomRootRenderer_24;
  }
  get _RootRenderer_25():any {
    if ((this.__RootRenderer_25 == null)) { (this.__RootRenderer_25 = import38._createConditionalRootRenderer(this._DomRootRenderer_24,this.parent.get(import38.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_25;
  }
  get _DomSanitizer_26():import17.DomSanitizerImpl {
    if ((this.__DomSanitizer_26 == null)) { (this.__DomSanitizer_26 = new import17.DomSanitizerImpl()); }
    return this.__DomSanitizer_26;
  }
  get _Sanitizer_27():any {
    if ((this.__Sanitizer_27 == null)) { (this.__Sanitizer_27 = this._DomSanitizer_26); }
    return this.__Sanitizer_27;
  }
  get _ViewUtils_28():import18.ViewUtils {
    if ((this.__ViewUtils_28 == null)) { (this.__ViewUtils_28 = new import18.ViewUtils(this._RootRenderer_25,this._Sanitizer_27)); }
    return this.__ViewUtils_28;
  }
  get _IterableDiffers_29():any {
    if ((this.__IterableDiffers_29 == null)) { (this.__IterableDiffers_29 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_29;
  }
  get _KeyValueDiffers_30():any {
    if ((this.__KeyValueDiffers_30 == null)) { (this.__KeyValueDiffers_30 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_30;
  }
  get _SharedStylesHost_31():any {
    if ((this.__SharedStylesHost_31 == null)) { (this.__SharedStylesHost_31 = this._DomSharedStylesHost_22); }
    return this.__SharedStylesHost_31;
  }
  get _Title_32():import19.Title {
    if ((this.__Title_32 == null)) { (this.__Title_32 = new import19.Title()); }
    return this.__Title_32;
  }
  get _RadioControlRegistry_33():import20.RadioControlRegistry {
    if ((this.__RadioControlRegistry_33 == null)) { (this.__RadioControlRegistry_33 = new import20.RadioControlRegistry()); }
    return this.__RadioControlRegistry_33;
  }
  get _FormBuilder_34():import21.FormBuilder {
    if ((this.__FormBuilder_34 == null)) { (this.__FormBuilder_34 = new import21.FormBuilder()); }
    return this.__FormBuilder_34;
  }
  get _ROUTER_CONFIGURATION_35():any {
    if ((this.__ROUTER_CONFIGURATION_35 == null)) { (this.__ROUTER_CONFIGURATION_35 = {}); }
    return this.__ROUTER_CONFIGURATION_35;
  }
  get _LocationStrategy_36():any {
    if ((this.__LocationStrategy_36 == null)) { (this.__LocationStrategy_36 = import7.provideLocationStrategy(this.parent.get(import39.PlatformLocation),this.parent.get(import40.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_35)); }
    return this.__LocationStrategy_36;
  }
  get _Location_37():import22.Location {
    if ((this.__Location_37 == null)) { (this.__Location_37 = new import22.Location(this._LocationStrategy_36)); }
    return this.__Location_37;
  }
  get _UrlSerializer_38():import23.DefaultUrlSerializer {
    if ((this.__UrlSerializer_38 == null)) { (this.__UrlSerializer_38 = new import23.DefaultUrlSerializer()); }
    return this.__UrlSerializer_38;
  }
  get _RouterOutletMap_39():import24.RouterOutletMap {
    if ((this.__RouterOutletMap_39 == null)) { (this.__RouterOutletMap_39 = new import24.RouterOutletMap()); }
    return this.__RouterOutletMap_39;
  }
  get _NgModuleFactoryLoader_40():import25.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_40 == null)) { (this.__NgModuleFactoryLoader_40 = new import25.SystemJsNgModuleLoader(this._Compiler_16,this.parent.get(import25.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_40;
  }
  get _ROUTES_41():any[] {
      if ((this.__ROUTES_41 == null)) { (this.__ROUTES_41 = [[
        {
          path: '',
          redirectTo: '/messages',
          pathMatch: 'full'
        }
        ,
        {
          path: 'messages',
          component: import41.MessagesComponent
        }
        ,
        {
          path: 'auth',
          component: import42.AuthenticationComponent,
          children: [
            {
              path: '',
              redirectTo: 'signup',
              pathMatch: 'full'
            }
            ,
            {
              path: 'signup',
              component: import43.SignupComponent
            }
            ,
            {
              path: 'signin',
              component: import44.SigninComponent
            }
            ,
            {
              path: 'logout',
              component: import45.LogoutComponent
            }

          ]

        }

      ]
    ]); }
    return this.__ROUTES_41;
  }
  get _Router_42():any {
    if ((this.__Router_42 == null)) { (this.__Router_42 = import7.setupRouter(this._ApplicationRef_15,this._UrlSerializer_38,this._RouterOutletMap_39,this._Location_37,this,this._NgModuleFactoryLoader_40,this._Compiler_16,this._ROUTES_41,this._ROUTER_CONFIGURATION_35,this.parent.get(import46.UrlHandlingStrategy,(null as any)))); }
    return this.__Router_42;
  }
  get _ActivatedRoute_43():any {
    if ((this.__ActivatedRoute_43 == null)) { (this.__ActivatedRoute_43 = import7.rootRoute(this._Router_42)); }
    return this.__ActivatedRoute_43;
  }
  get _PreloadAllModules_47():import26.PreloadAllModules {
    if ((this.__PreloadAllModules_47 == null)) { (this.__PreloadAllModules_47 = new import26.PreloadAllModules()); }
    return this.__PreloadAllModules_47;
  }
  get _ROUTER_INITIALIZER_48():any {
    if ((this.__ROUTER_INITIALIZER_48 == null)) { (this.__ROUTER_INITIALIZER_48 = import7.initialRouterNavigation(this._Router_42,this._ApplicationRef_15,this._RouterPreloader_46,this._ROUTER_CONFIGURATION_35)); }
    return this.__ROUTER_INITIALIZER_48;
  }
  get _APP_BOOTSTRAP_LISTENER_49():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_49 == null)) { (this.__APP_BOOTSTRAP_LISTENER_49 = [this._ROUTER_INITIALIZER_48]); }
    return this.__APP_BOOTSTRAP_LISTENER_49;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._ROUTER_FORROOT_GUARD_5 = import7.provideForRootGuard(this.parent.get(import47.Router,(null as any)));
    this._RouterModule_6 = new import7.RouterModule(this._ROUTER_FORROOT_GUARD_5);
    this._ReactiveFormsModule_7 = new import6.ReactiveFormsModule();
    this._AppModule_8 = new import1.AppModule();
    this._ErrorHandler_11 = import4.errorHandler();
    this._ApplicationInitStatus_12 = new import9.ApplicationInitStatus(this.parent.get(import9.APP_INITIALIZER,(null as any)));
    this._Testability_13 = new import10.Testability(this.parent.get(import37.NgZone));
    this._ApplicationRef__14 = new import11.ApplicationRef_(this.parent.get(import37.NgZone),this.parent.get(import48.Console),this,this._ErrorHandler_11,this,this._ApplicationInitStatus_12,this.parent.get(import10.TestabilityRegistry,(null as any)),this._Testability_13);
    this._NoPreloading_44 = new import26.NoPreloading();
    this._PreloadingStrategy_45 = this._NoPreloading_44;
    this._RouterPreloader_46 = new import26.RouterPreloader(this._Router_42,this._NgModuleFactoryLoader_40,this._Compiler_16,this,this._PreloadingStrategy_45);
    return this._AppModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_5; }
    if ((token === import7.RouterModule)) { return this._RouterModule_6; }
    if ((token === import6.ReactiveFormsModule)) { return this._ReactiveFormsModule_7; }
    if ((token === import1.AppModule)) { return this._AppModule_8; }
    if ((token === import49.LOCALE_ID)) { return this._LOCALE_ID_9; }
    if ((token === import8.NgLocalization)) { return this._NgLocalization_10; }
    if ((token === import50.ErrorHandler)) { return this._ErrorHandler_11; }
    if ((token === import9.ApplicationInitStatus)) { return this._ApplicationInitStatus_12; }
    if ((token === import10.Testability)) { return this._Testability_13; }
    if ((token === import11.ApplicationRef_)) { return this._ApplicationRef__14; }
    if ((token === import11.ApplicationRef)) { return this._ApplicationRef_15; }
    if ((token === import12.Compiler)) { return this._Compiler_16; }
    if ((token === import34.APP_ID)) { return this._APP_ID_17; }
    if ((token === import51.DOCUMENT)) { return this._DOCUMENT_18; }
    if ((token === import13.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_19; }
    if ((token === import14.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_20; }
    if ((token === import14.EventManager)) { return this._EventManager_21; }
    if ((token === import15.DomSharedStylesHost)) { return this._DomSharedStylesHost_22; }
    if ((token === import52.AnimationDriver)) { return this._AnimationDriver_23; }
    if ((token === import16.DomRootRenderer)) { return this._DomRootRenderer_24; }
    if ((token === import53.RootRenderer)) { return this._RootRenderer_25; }
    if ((token === import17.DomSanitizer)) { return this._DomSanitizer_26; }
    if ((token === import54.Sanitizer)) { return this._Sanitizer_27; }
    if ((token === import18.ViewUtils)) { return this._ViewUtils_28; }
    if ((token === import55.IterableDiffers)) { return this._IterableDiffers_29; }
    if ((token === import56.KeyValueDiffers)) { return this._KeyValueDiffers_30; }
    if ((token === import15.SharedStylesHost)) { return this._SharedStylesHost_31; }
    if ((token === import19.Title)) { return this._Title_32; }
    if ((token === import20.RadioControlRegistry)) { return this._RadioControlRegistry_33; }
    if ((token === import21.FormBuilder)) { return this._FormBuilder_34; }
    if ((token === import7.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_35; }
    if ((token === import40.LocationStrategy)) { return this._LocationStrategy_36; }
    if ((token === import22.Location)) { return this._Location_37; }
    if ((token === import23.UrlSerializer)) { return this._UrlSerializer_38; }
    if ((token === import24.RouterOutletMap)) { return this._RouterOutletMap_39; }
    if ((token === import57.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_40; }
    if ((token === import58.ROUTES)) { return this._ROUTES_41; }
    if ((token === import47.Router)) { return this._Router_42; }
    if ((token === import59.ActivatedRoute)) { return this._ActivatedRoute_43; }
    if ((token === import26.NoPreloading)) { return this._NoPreloading_44; }
    if ((token === import26.PreloadingStrategy)) { return this._PreloadingStrategy_45; }
    if ((token === import26.RouterPreloader)) { return this._RouterPreloader_46; }
    if ((token === import26.PreloadAllModules)) { return this._PreloadAllModules_47; }
    if ((token === import7.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_48; }
    if ((token === import34.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_49; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__14.ngOnDestroy();
    this._RouterPreloader_46.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);