/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './messages.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './message-input.component';
import * as import9 from './message-input.component.ngfactory';
import * as import10 from './message-list.component';
import * as import11 from './message-list.component.ngfactory';
import * as import12 from './message.service';
export class Wrapper_MessagesComponent {
  /*private*/ _eventHandler:Function;
  context:import0.MessagesComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.MessagesComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_MessagesComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_MessagesComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.MessagesComponent>;
  _MessagesComponent_0_3:Wrapper_MessagesComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MessagesComponent_Host0,renderType_MessagesComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-messages',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_MessagesComponent0(this.viewUtils,this,0,this._el_0);
    this._MessagesComponent_0_3 = new Wrapper_MessagesComponent();
    this.compView_0.create(this._MessagesComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._MessagesComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MessagesComponent) && (0 === requestNodeIndex))) { return this._MessagesComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MessagesComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const MessagesComponentNgFactory:import7.ComponentFactory<import0.MessagesComponent> = new import7.ComponentFactory<import0.MessagesComponent>('app-messages',View_MessagesComponent_Host0,import0.MessagesComponent);
const styles_MessagesComponent:any[] = ([] as any[]);
var renderType_MessagesComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_MessagesComponent,{});
export class View_MessagesComponent0 extends import1.AppView<import0.MessagesComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  compView_3:import1.AppView<import8.MessageInputComponent>;
  _MessageInputComponent_3_3:import9.Wrapper_MessageInputComponent;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  compView_10:import1.AppView<import10.MessageListComponent>;
  _MessageListComponent_10_3:import11.Wrapper_MessageListComponent;
  _text_11:any;
  _text_12:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MessagesComponent0,renderType_MessagesComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'app-message-input',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_3 = new import9.View_MessageInputComponent0(this.viewUtils,this,3,this._el_3);
    this._MessageInputComponent_3_3 = new import9.Wrapper_MessageInputComponent(this.parentView.injectorGet(import12.MessageService,this.parentIndex));
    this.compView_3.create(this._MessageInputComponent_3_3.context);
    this._text_4 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,parentRenderNode,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'app-message-list',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_10 = new import11.View_MessageListComponent0(this.viewUtils,this,10,this._el_10);
    this._MessageListComponent_10_3 = new import11.Wrapper_MessageListComponent(this.parentView.injectorGet(import12.MessageService,this.parentIndex));
    this.compView_10.create(this._MessageListComponent_10_3.context);
    this._text_11 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._text_12 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import8.MessageInputComponent) && (3 === requestNodeIndex))) { return this._MessageInputComponent_3_3.context; }
    if (((token === import10.MessageListComponent) && (10 === requestNodeIndex))) { return this._MessageListComponent_10_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MessageInputComponent_3_3.ngDoCheck(this,this._el_3,throwOnChange);
    this._MessageListComponent_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    this.compView_3.detectChanges(throwOnChange);
    this.compView_10.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_3.destroy();
    this.compView_10.destroy();
  }
}